apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: sockeye-trigger
  namespace: default
spec:
  filter: {}
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: display
