apiVersion: sources.knative.dev/v1alpha1
kind: SinkBinding
metadata:
  name: receiver-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: receiver
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receiver
spec:
  template:
    spec:
      containers:
      - image: github.com/mattmoor/knobots-broadcast/cmd/receiver
